DROP TABLE if exists accelerometer;

CREATE TABLE ACCELEROMETER
(
ID        	BIGINT PRIMARY KEY,
VERSION		BIGINT,
ACTIVITY	VARCHAR	(50),
ALT			VARCHAR	(50),
DEVICE		VARCHAR	(50),
DIFFX		DOUBLE,
DIFFY		DOUBLE,
DIFFZ		DOUBLE,
LAT			VARCHAR(50),
LON			VARCHAR(50),
TIME		VARCHAR(50),
XCOORD		VARCHAR(50),
YCOORD		VARCHAR(50),
ZCOORD		VARCHAR	(50)
)
PARTITION BY PRIMARY KEY
EXPIRE ENTRY WITH TIMETOLIVE 6000 ACTION DESTROY
hdfsstore (accelerometerMovements) WRITEONLY;

